import { DM_Sans } from "next/font/google"
import "./globals.css"
import Layout from "@/components/layout"

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  display: "swap",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
